name: "printArgsWithPyscript"
author: "nrd"
description: "Using python script to print the args which are passed in the command line"
inputs:
  firstarg:
    required: true
  secondarg:
    required: true
  thirdarg:
    required: true
  fourtharg:
    required: false

runs:
  using: "composite"
  steps:
  - name: Check Python Version
    run: python -V
    shell: bash  
  - name: list Action Repo
    working-directory: $GITHUB_ACTION_PATH
    run: |
      ls -la
    shell: bash
    env:
      GITHUB_ACTION_PATH: ${{ github.action_path }}    
  - name: Run Py Script 
    working-directory: $GITHUB_ACTION_PATH
    run: python ptest.py ${{ inputs.firstarg }} ${{ inputs.secondarg }} ${{ inputs.thirdarg }} ${{ inputs.fourtharg }}
    shell: bash
    env:
      GITHUB_ACTION_PATH: ${{ github.action_path }}
    
