name: "printArgsWithPyscript"
author: "nrd"
description: "Using python script to print the args which are passed in the command line"
inputs:
  firstarg:
    required: true
  secondarg:
    required: true
  thirdarg:
    required: true
  fourtharg:
    required: false

runs:
  using: "composite"
  steps:
  - name: Check Python Version
    run: python -V
    shell: bash  
  - name: list Action Repo
    env:
      GITHUB_ACTION_PATH: ${{ github.action_path }}  
    run: |
      cd $GITHUB_ACTION_PATH
      ls -la
    shell: bash        
  - name: Run Py Script
    env:
      GITHUB_ACTION_PATH: ${{ github.action_path }}   
    run: python ptest.py ${{ inputs.firstarg }} ${{ inputs.secondarg }} ${{ inputs.thirdarg }} ${{ inputs.fourtharg }}
    shell: bash
    
    
